### ISSUE TITLE
Description at the beginning of README

### ISSUE THREAD

**Issue by lorem-ipsumm** [aeshthetic/dixie#5]
As a non F# developer, I was driven away by the lack of description at the very beginning. A brief 1-2 line description at the beginning of the README would be ideal, so I can get a feel for what I am looking at. Even though I do not program in F# having a description allows me to follow the example code better

**Comment by aeshthetic** [comment]
I agree wholeheartedly. Thank you for expressing your concerns 😄 .
I'll assign this to myself and hopefully have it done in no time.

**Comment by aeshthetic** [comment]
Hopefully the description I've added suffices. If this isn't the case I'll gladly re-open this issue.
